# Use a imagem base Python
FROM python:3.9-slim

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo de requisitos
COPY requirements.txt .

# Instale as dependências Python
RUN pip install -r requirements.txt

# Copie o script Python
COPY app.py .

# Defina o comando padrão a ser executado quando o contêiner for iniciado
CMD ["python", "app.py"]